services:
  postgres:
    build:
      context: ./postgres
    image: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  api-gateway:
    build:
      context: ./gateway
    image: api-gateway
    container_name: agrops-api-gateway
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/agrops
    image: agrops-frontend
    container_name: agrops-frontend
    depends_on:
      - api-gateway
    ports:
      - "80:80"