version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - UVICORN=reload

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma:/chroma

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1234
    ports:
      - "9000:9000"

volumes:

  chroma:
  ollama: