from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from identity.domain.entities import IdentityUser


@runtime_checkable
class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password: str, password_hash: str) -> bool: ...


@runtime_checkable
class TokenSigner(Protocol):
    def encode(
        self,
        user_id,
        email: str,
        expires_minutes: int | None = None,
        jti: str | None = None,
        token_use: str = "session",
    ) -> str: ...

    def decode(self, token: str) -> dict[str, Any]: ...

    @property
    def expire_minutes(self) -> int: ...


@runtime_checkable
class UserRepository(Protocol):
    async def get_orm_by_id(self, user_id) -> Any: ...

    async def get_by_email(self, email: str) -> dict[str, Any] | None: ...

    async def email_exists(self, email: str) -> bool: ...

    async def register(
        self, name: str, email: str, password_hash: str
    ) -> UUID | str: ...

    async def list_users(self) -> list[dict[str, Any]]: ...

    async def list_roles(self) -> list[dict[str, Any]]: ...

    async def list_user_roles(self, user_id) -> list[dict[str, Any]]: ...

    async def is_admin(self, user_id) -> bool: ...

    async def ensure_agrotech(self, user_id) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


@runtime_checkable
class TokenStore(Protocol):
    async def revoke_session(self, token: str, expires_at) -> None: ...

    async def assert_access_token_active(self, jti: str, user_id) -> None: ...


@runtime_checkable
class AccountRepository(Protocol):
    async def ensure_tables(self) -> None: ...

    async def resolve_managed_user(
        self, current_user, user_id, organization_id=None
    ): ...

    async def profile_payload(self, user) -> dict[str, Any]: ...

    async def update_name(self, user_id, name: str) -> None: ...

    async def upsert_profile(self, user_id, data: dict[str, Any]) -> None: ...

    async def get_avatar_path(self, user_id) -> str | None: ...

    async def clear_avatar(self, user_id) -> None: ...

    async def list_tokens(self, user_id, kind: str | None = None) -> list[dict]: ...

    async def insert_token(self, row: dict[str, Any]) -> None: ...

    async def revoke_token(self, token_id, user_id): ...

    async def usage(self, user_id) -> dict[str, int]: ...

    async def analytics(self, user_id) -> dict[str, Any]: ...

    async def projects(self, organization_id, user_id) -> list[dict]: ...

    async def list_admins(self, user_id, organization_id: str | None) -> list[dict]: ...

    async def list_support(self, user_id, is_admin: bool) -> list[dict]: ...

    async def create_support(self, row: dict[str, Any]) -> None: ...

    async def list_managed_users(
        self, organization_id, query: str, limit: int, offset: int
    ) -> list[dict]: ...

    async def is_org_member(self, organization_id, user_id) -> bool: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
